function [scenario, egoVehicle] = drive1()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.8 (R2020a) and Automated Driving Toolbox 3.1 (R2020a).
% Generated on: 23-Jul-2026 15:44:19

% Construct a drivingScenario object.
scenario = drivingScenario;
u = 30;
% Add all road segments
roadCenters = [55.8 5.9 0;
    42.4 16.4 0;
    37.3 18.3 0;
    28.1 25.6 0;
    20.3 17.9 0;
    18.7 -5.3 0;
    14.6 10.6 0;
    4.6 12.8 0;
    2.2 21.3 0;
    -1.8 30.2 0;
    -4.8 17.9 0;
    -4.9 5.5 0;
    1.6 -4.4 0;
    10.8 -7.1 0;
    14.9 -13.1 0;
    26 -16.8 0;
    42.7 -31.8 0;
    51.1 -10.1 0;
    53.4 -3.3 0;
    55.8 5.9 0;
    55.8 5.9 0];
road(scenario, roadCenters);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [32.3 -24.7 0]);


trajectory(ego vehicle, waypoints,u);
