% Reverse-Engineered Energy-Based Impedance Estimator in MATLAB
% Evaluates total haptic energy components and updates k and b dynamically

clear; clc; close all;

%% Simulation Parameters
dt = 0.001;          % Sampling period (s)
T_total = 2.0;       % Total simulation time (s)
N_steps = round(T_total / dt);

% System & Environment Parameters
m = 0.5;             % Device mass (kg)
x_wall = 0.0;        % Wall position (m)

% True target environment values to be reverse-engineered
k_true = 10000;      % True stiffness (N/m)
b_true = 20;         % True damping (Ns/m)

% Preallocation
t = zeros(N_steps, 1);
x = zeros(N_steps, 1);
v = zeros(N_steps, 1);
F_h = zeros(N_steps, 1);
E_spring = zeros(N_steps, 1);
E_damping = zeros(N_steps, 1);
E_total = zeros(N_steps, 1);

% Estimated parameters initialized adaptively
k_est = zeros(N_steps, 1);
b_est = zeros(N_steps, 1);
k_est(1) = 5000;     % Initial guess for stiffness
b_est(1) = 5;        % Initial guess for damping

%% Main Simulation Loop
for n = 2:N_steps
    t(n) = (n - 1) * dt;
    
    % Human interaction force profile
    if t(n) > 0.2 && t(n) < 1.7
        F_h(n) = 12 * sin(2 * pi * 2.5 * (t(n) - 0.2));
    else
        F_h(n) = 0;
    end
    
    % Penetration distance into the virtual wall
    x_err = x(n-1) - x_wall;
    
    if x_err < 0
        % Actual physical interaction force generated by true parameters
        F_wall = -k_true * x_err - b_true * v(n-1);
    else
        F_wall = 0;
    end
    
    % Plant Dynamics Update
    accel = (F_h(n) - F_wall) / m;
    v(n) = v(n-1) + accel * dt;
    x(n) = x(n-1) + v(n) * dt;
    
    % --- ENERGY DECOMPOSITION ---
    if x_err < 0
        % Potential energy stored in the virtual spring: E_k = 0.5 * k * x^2
        E_spring(n) = 0.5 * k_est(n-1) * (x_err^2);
        
        % Dissipated energy term integrated over time: E_b = integral(b * v^2) dt
        dE_damping = b_est(n-1) * (v(n)^2) * dt;
        E_damping(n) = E_damping(n-1) + dE_damping;
    else
        E_spring(n) = 0;
        E_damping(n) = E_damping(n-1); % Hold energy state outside wall
    end
    
    % Total Tracked System Energy
    E_total(n) = E_spring(n) + E_damping(n);
    
    % --- REVERSE ENGINEERING / PARAMETER ADAPTATION ---
    % Update estimates based on energy error feedback loops
    if x_err < 0 && abs(x_err) > 1e-4
        % Reverse-engineer stiffness from potential energy constraint: k = 2 * E_k / x^2
        k_error = (-F_wall - (-k_est(n-1)*x_err - b_est(n-1)*v(n-1))); 
        
        % Gradient adaptation rules for stiffness and damping estimates
        k_est(n) = max(0, k_est(n-1) + 0.5 * k_error * x_err * dt);
        b_est(n) = max(0, b_est(n-1) + 0.1 * k_error * v(n) * dt);
    else
        k_est(n) = k_est(n-1);
        b_est(n) = b_est(n-1);
    end
end

%% Plotting Results
figure('Name', 'Reverse-Engineered Energy and Impedance Estimator', 'Position', [100, 100, 900, 700]);

subplot(3, 1, 1);
plot(t, x * 1e3, 'LineWidth', 1.5);
ylabel('Penetration (mm)');
title('Haptic Interaction with Energy-Based Impedance Estimation');
grid on;

subplot(3, 1, 2);
plot(t, E_total, 'b', t, E_spring, 'r--', t, E_damping, 'g:', 'LineWidth', 1.2);
legend('Total Energy', 'Spring Energy (E_k)', 'Damping Energy (E_b)', 'Location', 'NorthWest');
ylabel('Energy (J)');
grid on;

subplot(3, 1, 3);
plot(t, k_est, 'r', t, b_est * 100, 'b', 'LineWidth', 1.2); % scaled b for visibility
legend('Est. Stiffness (k)', 'Est. Damping (b x 100)', 'Location', 'NorthWest');
xlabel('Time (s)');
ylabel('Parameters');
grid on;
