site_name: CAPTipedia Documentation 
site_url: https://sofierazou.github.io/my-docs-site/

theme:
  name: material
  font: 
    text: Merriweather Sans 
    code: Red Hat Mono 
  features:
    - content.code.annotate  # Enables interactive code line notes
    - content.code.copy      # Adds a copy button to code blocks
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: purple
      
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: pink
      accent: purple

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
